config/routes.rb
Rails.application.routes.draw do
  devise_for :hosts

  get 'about', to: 'home#about', as: :about
  get 'visit/:host_url_identifier', to: 'visits#new', as: :visit
  post 'visit/:host_url_identifier', to: 'visits#create'
  get :visits, to: 'visits#index'

  namespace :admin do
    resources :visits, only: %i[index update destroy], param: :token
    resource :qr_code, only: :show
    resources :downloads, only: %i[new create]
    resource :settings, only: %i[edit update]
    root to: 'home#index'
  end

  post '/', to: 'home#index'

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host.rb
class Host < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :visits, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true

  validates :url_identifier, presence: true
  validates :url_identifier, uniqueness: true

  before_validation :initialize_url_identifier

  def visit_url
    Rails.application.routes.url_helpers.visit_url(host_url_identifier: self)
  end

  def to_param
    url_identifier
  end

  private

  def initialize_url_identifier
    self.url_identifier ||= SecureRandom.base58(4)
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :host
  validates :visited_at, :contact, :token, presence: true
  validates :token, uniqueness: { scope: :host_id }

  before_validation :initialize_visited_at
  before_validation :initialize_token

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :unconfirmed, -> { where(confirmed_at: nil) }
  scope :of_uuid, ->(uuid) { where(uuid: uuid) }

  scope :antichronological, -> {
    order(visited_at: :desc).order(confirmed_at: :desc).order(:token)
  }

  scope :visited_at_on_date_in_time_zone, ->(date, time_zone) {
    where(
      "date(visited_at AT TIME ZONE 'UTC' AT TIME ZONE :time_zone) = :date",
      date: date,
      time_zone: time_zone
    )
  }

  def to_param
    token
  end

  def confirmed?
    confirmed_at.present?
  end

  def downloaded?
    downloaded_at.present?
  end

  def set_confirmed_at
    self.confirmed_at ||= Time.zone.now
  end

  def status
    return :rejected if destroyed? || new_record?
    return :confirmed if confirmed?

    :unconfirmed
  end

  def decorate
    @decorate ||= VisitDecorator.new(self)
  end

  private

  def initialize_visited_at
    self.visited_at ||= Time.zone.now
  end

  def initialize_token
    self.token ||= SecureRandom.base58(5)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_host!
end

app/controllers/admin/downloads_controller.rb
class Admin::DownloadsController < ApplicationController
  def new
    @form = Admin::DownloadForm.new(current_host, selected_date: Time.zone.today)
  end

  def create
    @form = Admin::DownloadForm.new(current_host, download_params)

    if @form.valid?
      service = VisitsDownloadService.new(current_host, @form.validated_selected_date)
      send_data(service.to_csv, filename: service.filename)
    else
      render :new
    end
  end

  private

  def download_params
    params.require(:admin_download).permit(:selected_date)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
    @unconfirmed_host_visits_count = current_host.visits.unconfirmed.count
  end
end

app/controllers/admin/qr_codes_controller.rb
class Admin::QrCodesController < Admin::BaseController
  layout 'qr_code'

  def show
    @qr_code = QrCodeService.new(current_host.visit_url)
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController
  def edit
    @settings_form = Admin::SettingsForm.new(current_host)
  end

  def update
    @settings_form = Admin::SettingsForm.new(current_host, admin_settings_params)

    if @settings_form.save
      flash[:notice] = 'Settings updated successfully.'
      redirect_to edit_admin_settings_path
    else
      render :edit
    end
  end

  private

  def admin_settings_params
    params.require(:admin_settings).permit(:name, :url_identifier, :auto_confirm_visits, :notes_enabled, :notes_text)
  end
end

app/controllers/admin/visits_controller.rb
class Admin::VisitsController < Admin::BaseController
  before_action :set_visit, only: %i[update destroy]

  def index
    @visit_statistics = VisitsStatisticsService.new(current_host).statistics
    @visits = current_host.visits.antichronological

    @visits = if confirmed_only?
                @visits.confirmed
              else
                @visits.unconfirmed
              end
  end

  def update
    form = Admin::VisitForm.new(@visit, update_params)
    form.save

    broadcast_change(visit: form.object)

    redirect_to admin_visits_path
  end

  def destroy
    @visit.destroy
    broadcast_change(visit: @visit)

    redirect_to admin_visits_path
  end

  private

  def set_visit
    @visit = current_host.visits.find_by!(token: params[:token])
  end

  def confirmed_only?
    filter_params&.dig(:status) == 'confirmed'
  end

  def update_params
    params.require(:admin_visit).permit(:notes)
  end

  def filter_params
    params[:filter]&.permit(:status)
  end

  def broadcast_change(visit:)
    if visit.destroyed?
      VisitChannel.broadcast_to(visit, partial: nil)
    else
      partial = self.class.render layout: false, partial: 'visits/list_item', locals: { visit: visit }
      VisitChannel.broadcast_to(visit, partial: partial)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_uuid
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def after_sign_in_path_for(_resource)
    admin_root_path
  end

  def initialize_uuid
    session[:uuid] ||= cookies.signed[:uuid] || SecureRandom.uuid
    cookies.signed[:uuid] = session[:uuid]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @goto_hosts_form = GotoHostsForm.new(goto_hosts_params)
    @visits_count = Visit.of_uuid(session[:uuid]).count

    redirect_to visit_path(@goto_hosts_form.host) if @goto_hosts_form.validatable? && @goto_hosts_form.valid?
  end

  def about; end

  private

  def goto_hosts_params
    params[:goto_hosts_form]&.permit(:host_url_identifier)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    @visits = Visit.joins(:host)
                   .includes(:host)
                   .of_uuid(session[:uuid])
                   .antichronological
  end

  def new
    @visit_form = VisitForm.new(host.visits.new)
  end

  def create
    @visit_form = VisitForm.new(host.visits.new, visit_params)

    if @visit_form.save
      redirect_to visits_url
    else
      render :new
    end
  end

  private

  def visit_params
    params.require(:visit)
          .permit(:name, :contact, :notes)
          .merge(uuid: session[:uuid])
  end

  def host
    @host = Host.find_by!(url_identifier: params[:host_url_identifier])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(file_name)
    Pathname.new("app/assets/images/#{file_name}").read
  end
end

app/views/admin/home/index.html.haml
.text-center.mt-20.mb-6.px-4
  %h1.text-sm.mb-0.pb-0.leading-tight.text-indigo-400.tracking-wide= t('.admin_area')
  .text-indigo-600.text-4xl= "#{current_host.name}"

%section.bg-gradient-to-r.from-indigo-500.to-indigo-500.via-indigo-600.pt-10.pb-16.text-indigo-100.px-4
  .container.mx-auto.text-center
    .mx-auto{ class: 'md:w-1/2' }
      .w-full
        %svg.mx-auto.h-20.w-20{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M0 0h24v24H0z", :stroke => "none"}
          %rect{:height => "6", :rx => "1", :width => "6", :x => "4", :y => "4"}
          %line{:x1 => "7", :x2 => "7", :y1 => "17", :y2 => "17.01"}
          %rect{:height => "6", :rx => "1", :width => "6", :x => "14", :y => "4"}
          %line{:x1 => "7", :x2 => "7", :y1 => "7", :y2 => "7.01"}
          %rect{:height => "6", :rx => "1", :width => "6", :x => "4", :y => "14"}
          %line{:x1 => "17", :x2 => "17", :y1 => "7", :y2 => "7.01"}
          %line{:x1 => "14", :x2 => "17", :y1 => "14", :y2 => "14"}
          %line{:x1 => "20", :x2 => "20", :y1 => "14", :y2 => "14.01"}
          %line{:x1 => "14", :x2 => "14", :y1 => "14", :y2 => "17"}
          %line{:x1 => "14", :x2 => "17", :y1 => "20", :y2 => "20"}
          %line{:x1 => "17", :x2 => "20", :y1 => "17", :y2 => "17"}
          %line{:x1 => "20", :x2 => "20", :y1 => "17", :y2 => "20"}
      .w-full.mt-6
        = link_to t('.show_qr_code'),admin_qr_code_path, class: 'py-2 px-5 inline-block bg-white text-indigo-900 bg-white mx-auto hover:bg-indigo-400 hover:text-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-200'
      .text-sm.mt-8.tracking-wide.leading-5
        %p
          = t('.let_customers_register_themselves')
        %p.mt-2
          = t('.scanning_the_code_takes_customers_to_form')
        %p.mt-2
          = t('.consider_printing_the_qr_code')

%section.py-20.text-black.text-center.pt-16.pb-20.px-4
  .container.mx-auto
    .mx-auto{ class: 'md:w-1/2' }
      .w-full.text-indigo-600
        %svg.mx-auto.h-20.w-20{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M0 0h24v24H0z", :stroke => "none"}
          %circle{:cx => "9", :cy => "7", :r => "4"}
          %path{:d => "M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"}
          %path{:d => "M16 3.13a4 4 0 0 1 0 7.75"}
          %path{:d => "M21 21v-2a4 4 0 0 0 -3 -3.85"}
      .w-full.mt-6
        = link_to t('.manage_visits'), admin_visits_path, class: 'py-2 px-5 inline-block bg-indigo-400 text-black hover:bg-indigo-600 hover:text-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-200'
      .text-sm.mt-8
        .tracking-wide
          = t('.view_confirm_or_remove_visits')
        - if @unconfirmed_host_visits_count.positive?
          %p.tracking-wide.mt-2
            = t('.you_currently_have')
            = link_to t('.unconfirmed_with_count', count: @unconfirmed_host_visits_count),
                      admin_visits_path,
                      class: 'text-status text-status--hint transition duration-100 ease-in-out hover:bg-yellow-400'
            = t('.visits_period', count:@unconfirmed_host_visits_count)

%section.bg-gradient-to-r.from-indigo-500.to-indigo-500.via-indigo-600.pt-16.pb-20.text-indigo-100.px-4
  .container.mx-auto.text-center
    .mx-auto{ class: 'md:w-1/2' }
      .w-full
        %svg.mx-auto.h-20.w-20{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M0 0h24v24H0z", :fill => "none", :stroke => "none"}
          %path{:d => "M19 18a3.5 3.5 0 0 0 0 -7h-1a5 4.5 0 0 0 -11 -2a4.6 4.4 0 0 0 -2.1 8.4"}
          %line{:x1 => "12", :x2 => "12", :y1 => "13", :y2 => "22"}
          %polyline{:points => "9 19 12 22 15 19"}
      .w-full.mt-6
        = link_to t('.download_visits'), new_admin_download_path, class: 'py-2 px-5 inline-block bg-white text-indigo-900 bg-white mx-auto hover:bg-indigo-400 hover:text-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-200'
      .text-sm.mt-8
        = t('.download_visits_from_given_dates')

%section.py-20.text-black.text-center.pt-16.pb-20.px-4
  .container.mx-auto.text-center
    .mx-auto{ class: 'md:w-1/2' }
      .w-full.text-indigo-600
        %svg.mx-auto.h-20.w-20{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M0 0h24v24H0z", :stroke => "none"}
          %path{:d => "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"}
          %circle{:cx => "12", :cy => "12", :r => "3"}
      .w-full.mt-6
        = link_to t('.account_settings'), edit_admin_settings_path, class: 'py-2 px-5 inline-block bg-indigo-400 text-black hover:bg-indigo-600 hover:text-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-200'
      .text-sm.mt-8
        = t('.change_your_settings')

.text-center.mt-10.px-4
  = link_to t('shared.sign_out'), destroy_host_session_path, method: :delete, class: 'text-pink-500 hover:text-indigo-500 transition duration-100 ease-in-out'

app/views/admin/settings/edit.html.haml
.text-center.mt-6.mb-10.px-4
  = link_to t('shared.back'), admin_root_path, class: 'text-pink-500 hover:text-indigo-500 transition duration-100 ease-in-out'

.text-center.mt-10.px-4
  %h1.text-4xl.text-indigo-600
    = t('.account_settings')

%section.bg-gradient-to-r.from-indigo-500.to-indigo-500.via-indigo-600.pt-10.pb-16.px-4
  .container.mx-auto.text-left
    .mx-auto{ class: 'md:w-1/2' }
      = form_with model: @settings_form, url: admin_settings_path do |f|
        .my-8
          = f.label :name, class: 'text-white text-xs'
          = f.text_field :name, class: 'w-full'
          = render 'shared/forms/field_error_messages', form: @settings_form, column: :name

        .my-8
          %div{ data: { controller: 'visit-url-preview' } }
            = f.label :url_identifier, 'URL identifier', class: 'text-white text-xs'
            = f.text_field :url_identifier, class: 'w-full', data: { action: 'keyup->visit-url-preview#updatePreview', target: 'visit-url-preview.urlIdentifierInput' }
            = render 'shared/forms/field_error_messages', form: @settings_form, column: :url_identifier

            .text-indigo-100.text-xs.mt-4.mb-0
              = t('.this_is_the_last_part_of_your_public_url_colon')

              .bg-indigo-200.p-1.my-2.text-indigo-800.font-mono
                - *base_url, url_identifier = @settings_form.calculated_visit_url.rpartition('/')
                = "#{base_url.join}"
                %output.inline.font-bold.text-base{ data: { target: 'visit-url-preview.urlIdentifierOutput' } }>= url_identifier

              = t('.it_may_only_contain_alphanumeric_and_dashes')

            .text-indigo-100.text-xs
              = t('.note_that_your_qr_code_changes_if_you_change_url_identifier_html')

        .my-8
          = f.label :auto_confirm_visits, class: 'text-white text-xs'
          .text-indigo-200.text-xs.mt-1
            = t('.when_enabled_visits_are_confirmed_automatically')

          = f.check_box :auto_confirm_visits

        .my-8{ 'data-controller': 'admin-notes-settings' }
          .mb-4
            = f.label :notes_enabled, class: 'text-white text-xs'
            .text-indigo-200.text-xs.mt-1
              = t('.use_field_to_ask_guest_for_additional_information')

            = f.check_box :notes_enabled, data: { action: 'admin-notes-settings#toggleNotesText', target: 'admin-notes-settings.checkbox' }

          .mt-6{ data: { target: 'admin-notes-settings.textarea' } }
            = f.label :notes_text, 'Notes text', class: 'text-white text-xs'
            = f.text_area :notes_text, class: 'w-full'
            .text-indigo-100.text-xs.mt-1
              = t('.text_will_be_shown_below_notes_field')
              %br
              = t('.describe_what_information_you_are_asking_for')

        .actions.my-8.text-right
          - if @settings_form.errors.any?
            = link_to t('shared.cancel'), edit_admin_settings_path, class: 'mr-6 text-gray-400  hover:text-white'
          = f.button nil, type: :submit, class: 'inline-flex items-center px-10 py-3 border border-transparent text-base leading-6 font-medium text-indigo-900 bg-white hover:bg-indigo-400 hover:text-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-200'

app/views/admin/visits/_status_unconfirmed.html.haml
.my-8.p-5.bg-white{ class: "border-status-#{visit.status}", data: { visit: { token: visit.token } } }
  = form_with model: Admin::VisitForm.new(visit) do |f|
    .flex.flex-wrap.cursor-pointer{ data: { action: 'click->admin-visits#toggleActionMenu' } }
      .w-full
        .flex.flex-wrap.sm:flex-no-wrap.text-xs
          .w-full
            .text-gray-500= visit.decorate.display_visited_at_in_hosts_time_zone
      .w-full
        .text-2xl= visit.token
      .w-full.mt-1
        .flex
          .flex-auto
            .text-indigo-600.text-xs.tracking-wider
              - if visit.name.present?
                = "#{visit.name} | "
              = visit.decorate.display_contact_scrambled_full

    .flex.flex-wrap.mt-5{ data: { target: 'admin-visits.actionMenu'} }
      .w-full
        .flex.flex-wrap
          = f.label :notes, class: 'w-full text-indigo-400 text-xs'
          = f.text_field :notes, class: 'bg-indigo-100 w-full border border-indigo-200', placeholder: t('.notes_placeholder')
        .flex.flex-wrap.text-center.sm:flex-no-wrap
          .w-full.my-2
            = f.submit nil, class: 'cursor-pointer w-full bg-green-500 hover:bg-green-600 transition duration-200 ease-in-out text-sm text-white tracking-wider'
          .w-full
            = link_to t('.remove'), admin_visit_path(visit), method: :delete, class: 'cursor-pointer w-full block p-3 bg-gray-200 transition duration-200 ease-in-out hover:bg-gray-300 text-sm text-gray-700 tracking-wider'

app/views/home/_hosts_section.html.haml
%section#host.bg-gradient-to-r.from-indigo-600.to-indigo-500.via-indigo-700.pt-10.pb-10.text-center.px-4
  %h2.text-4xl.bold.text-white= t('.hosts')

  .text-center.text-white.tracking-wide
    = t('.register_for_free_html')

  .flex.flex-wrap.my-5
    .w-full
      = link_to new_host_registration_path, class: 'inline-flex items-center px-10 py-3 border border-transparent text-base leading-6 font-medium text-indigo-900 bg-white hover:bg-indigo-400 hover:text-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-200' do
        %svg.h-5.w-5.-ml-3.mr-3{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M0 0h24v24H0z", :stroke => "none"}
          %path{:d => "M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4"}
          %line{:x1 => "13.5", :x2 => "17.5", :y1 => "6.5", :y2 => "10.5"}
        = t('shared.sign_up')

  .flex.flex-wrap
    .w-full.text-center.text-sm.my-3.text-indigo-300
      = t('.already_have_an_account_question')
      = link_to t('shared.sign_in'), new_host_session_path, class: 'ml-1 text-white hover:text-indigo-300 transition duration-100 ease-in-out'

app/views/home/index.html.haml
.my-10.px-4
  .border.border-red-300.bg-red-100.p-4.text-center
    .mb-2
      %p.text-lg.tracking-wide https://rumo.host will be discontinued by November 13th 2021.
    .mt-2.text-gray-500.text-sm
      %p The site will no longer be available after that date.
      %p All data will be permanently deleted.
      %p.mt-1 Thank you for using this service.

.text-center.mb-16.mt-10.px-4
  %h1.text-center.text-5xl.mb-0.leading-tight.text-blue-900
    Rumo is a
    %span.block
      digital
      %b.bg-clip-text.text-transparent.bg-gradient-to-r.from-blue-400.to-blue-400.via-green-500
        guestlist
  %p.text-xl.text-gray-800.mt-4
    which can be used for COVID-19 precautionary measures.

- if @visits_count.positive?
  %section#my-visits.bg-gradient-to-r.from-green-300.via-green-100.to-green-300.pt-5.pb-8.text-center.text-sm.px-4
    .text-xl
      Welcome back!

    .text-gray-900.mt-4.mb-5
      You have visited
      %b= pluralize(@visits_count, 'host')
      in the past 2 weeks.

    .w-full.mt-6
      = link_to 'Show my visits', visits_path, class: 'tracking-wide inline-block text-white bg-green-600 py-2 px-5 transition duration-200 ease-in-out hover:bg-white hover:text-green-800'

%section#guest.bg-gradient-to-r.from-blue-600.to-blue-600.via-blue-700.pt-10.pb-12.text-center.px-4
  %h2.text-4xl.text-white Guests

  .container.mx-auto
    .w-full.mx-auto{ class: 'md:w-1/2'}
      = form_with model: @goto_hosts_form, url: root_path do |f|
        = f.label :host_url_identifier, class: 'mb-1 text-xs text-gray-300 tracking-wide' do
          Enter your
          %b host's token

        .my-2
          .w-full
            .flex.justify-center
              .relative.flex.border.border-blue-300.border-r-0.w-full
                = f.text_field :host_url_identifier, class: 'outline-none w-full'
              = f.submit 'Go', class: 'relative-flex bg-blue-300 tracking-wide text-black transition ease-in-out hover:bg-blue-400 duration-200 cursor-pointer'
          - if f.object.errors.key?(:host_url_identifier)
            %span.text-xs.text-yellow-400= f.object.errors.messages[:host_url_identifier].join

  .container.mx-auto
    .w-full.my-4
      .text-center.text-gray-400 or

  .container.mx-auto
    .w-full.mx-auto{ class: 'md:w-1/2'}
      .flex.flex-wrap
        .w-full
          %svg.mx-auto.h-12.w-12.text-white{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.3", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M0 0h24v24H0z", :stroke => "none"}
            %path{:d => "M4 7v-1a2 2 0 0 1 2 -2h2"}
            %path{:d => "M4 17v1a2 2 0 0 0 2 2h2"}
            %path{:d => "M16 4h2a2 2 0 0 1 2 2v1"}
            %path{:d => "M16 20h2a2 2 0 0 0 2 -2v-1"}
            %line{:x1 => "5", :x2 => "19", :y1 => "12", :y2 => "12"}
        .w-full.mt-2
          .text-xs.text-gray-300
            Ask your host for the
            %span.font-bold.text-gray-100 QR code
            %br
            that automatically takes you to the registration form.


%section#how-it-works.text-center.my-20.px-4
  %h2.inline-block.text-4xl.font-bold.text-blue-500.tracking-wider How it works

  .text-center.tracking-wide.leading-relaxed.text-gray-800.mb-10.mt-6
    %p.my-6
      %b.block.tracking-wider.text-blue-500 Guests
      submit their contact data at the beginning of their visit.

    %p.my-6
      %b.block.tracking-wider.text-blue-500 Hosts
      validate and confirm visits if required.

    %p.my-6
      %b.block.tracking-wider.text-blue-500 Rumo
      keeps sensitive data
      %b private
      until they are needed for contact tracing.

    %p.mt-6
      = link_to 'Read more', about_path, class: 'text-pink-500 hover:text-indigo-500 transition duration-100 ease-in-out'

%section#host.bg-gradient-to-r.from-indigo-600.to-indigo-500.via-indigo-700.pt-10.pb-10.text-center.px-4
  %h2.text-4xl.bold.text-white Hosts

  .text-center.text-white.tracking-wide
    Register for
    %span.tracking-wider.underline free

  .flex.flex-wrap.my-5
    .w-full
      = link_to new_host_registration_path, class: 'inline-flex items-center px-10 py-3 border border-transparent text-base leading-6 font-medium text-indigo-900 bg-white hover:bg-indigo-400 hover:text-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-200' do
        %svg.h-5.w-5.-ml-3.mr-3{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M0 0h24v24H0z", :stroke => "none"}
          %path{:d => "M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4"}
          %line{:x1 => "13.5", :x2 => "17.5", :y1 => "6.5", :y2 => "10.5"}
        Sign up

  .flex.flex-wrap
    .w-full.text-center.text-sm.my-3.text-indigo-300
      Already have an account?
      = link_to 'Sign in', new_host_session_path, class: 'ml-1 text-white hover:text-indigo-300 transition duration-100 ease-in-out'